In [1]:
from sklearn.datasets import load_iris

In [2]:
import numpy as np

In [3]:
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
print(iris.data.shape)

(150, 4)


In [8]:
print(iris.target.shape)

(150,)


In [9]:
n_samples, n_features = iris.data.shape

In [10]:
print("Number of Samples = ",n_samples)
print('Number of Features = ',n_features)

Number of Samples =  150
Number of Features =  4


In [11]:
print(iris.data[0])

[5.1 3.5 1.4 0.2]


In [12]:
np.bincount(iris.target)

array([50, 50, 50], dtype=int32)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
x,y = iris.data,iris.target
Classifier = KNeighborsClassifier()

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.5,random_state=123)
print(train_y)
print(test_y)

[1 1 0 2 2 0 0 1 1 2 0 0 1 0 1 2 0 2 0 0 1 0 0 1 2 1 1 1 0 0 1 2 0 0 1 1 1
 2 1 1 1 2 0 0 1 2 2 2 2 0 1 0 1 1 0 1 2 1 2 2 0 1 0 2 2 1 1 2 2 1 0 1 1 2
 2]
[1 2 2 1 0 2 1 0 0 1 2 0 1 2 2 2 0 0 1 0 0 2 0 2 0 0 0 2 2 0 2 2 0 0 1 1 2
 0 0 1 1 0 2 2 2 2 2 1 0 0 2 0 0 1 1 1 1 2 1 2 0 2 1 0 0 2 1 2 2 0 1 1 2 0
 2]


In [17]:
print("All : ",np.bincount(y)/float(len(y))*100)
print("Train : ",np.bincount(train_y)/float(len(train_y))*100)
print("Test : ",np.bincount(test_y)/float(len(test_y))*100)

All :  [33.33333333 33.33333333 33.33333333]
Train :  [30.66666667 40.         29.33333333]
Test :  [36.         26.66666667 37.33333333]


In [18]:
train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.5,random_state=123,stratify=y)
print(train_y)
print(test_y)

[1 1 1 0 0 2 1 1 1 0 1 0 2 0 0 2 0 2 1 1 0 0 2 1 2 1 0 1 1 1 2 1 2 2 0 0 2
 2 0 0 2 2 2 2 0 2 0 2 1 1 0 2 2 0 2 1 2 1 2 1 1 0 0 1 2 0 0 2 2 1 0 1 0 0
 1]
[0 2 1 0 2 0 1 2 0 0 2 1 2 0 1 2 2 2 2 2 1 2 1 1 2 2 0 0 1 0 0 2 0 1 0 0 1
 1 2 2 0 1 0 1 1 2 0 1 1 1 0 2 2 2 1 0 0 1 1 0 2 1 0 2 0 2 1 1 2 0 2 1 0 0
 1]


In [19]:
print("All : ",np.bincount(y)/float(len(y))*100)
print("Train : ",np.bincount(train_y)/float(len(train_y))*100)
print("Test : ",np.bincount(test_y)/float(len(test_y))*100)

All :  [33.33333333 33.33333333 33.33333333]
Train :  [33.33333333 33.33333333 33.33333333]
Test :  [33.33333333 33.33333333 33.33333333]


In [20]:
Classifier.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [22]:
pred_y=Classifier.predict(test_x)
print("Accuracy : ",np.sum(pred_y==test_y)/float(len(test_y)))

Accuracy :  0.96


In [23]:
correct_idx=np.where(pred_y==test_y)[0]
print(correct_idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 45 46 47 48
 50 51 52 53 54 55 56 57 58 59 61 62 63 64 65 66 67 68 69 70 71 72 73 74]


In [24]:
incorrect_idx=np.where(pred_y!=test_y)[0]
print(incorrect_idx)

[44 49 60]


In [25]:
train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.5,random_state=123)
Classifier.fit(train_x,train_y)
pred_y=Classifier.predict(test_x)
print("Accuracy : ",np.sum(pred_y==test_y)/float(len(test_y)))

Accuracy :  0.9466666666666667


In [26]:
correct_idx=np.where(pred_y==test_y)[0]
print(correct_idx)

[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 24 25 26
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51
 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]


In [27]:
incorrect_idx=np.where(pred_y!=test_y)[0]
print(incorrect_idx)

[ 0  5 23 27]
