In [7]:
from sklearn.datasets import load_iris
iris = load_iris()

In [9]:
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [11]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [13]:
iris.target[0]

0

In [14]:
for i in range(len(iris.target)):
    print("Example %d: lable %s, feature %s" %(i,iris.target[i],iris.data[i]))

Example 0: lable 0, feature [5.1 3.5 1.4 0.2]
Example 1: lable 0, feature [4.9 3.  1.4 0.2]
Example 2: lable 0, feature [4.7 3.2 1.3 0.2]
Example 3: lable 0, feature [4.6 3.1 1.5 0.2]
Example 4: lable 0, feature [5.  3.6 1.4 0.2]
Example 5: lable 0, feature [5.4 3.9 1.7 0.4]
Example 6: lable 0, feature [4.6 3.4 1.4 0.3]
Example 7: lable 0, feature [5.  3.4 1.5 0.2]
Example 8: lable 0, feature [4.4 2.9 1.4 0.2]
Example 9: lable 0, feature [4.9 3.1 1.5 0.1]
Example 10: lable 0, feature [5.4 3.7 1.5 0.2]
Example 11: lable 0, feature [4.8 3.4 1.6 0.2]
Example 12: lable 0, feature [4.8 3.  1.4 0.1]
Example 13: lable 0, feature [4.3 3.  1.1 0.1]
Example 14: lable 0, feature [5.8 4.  1.2 0.2]
Example 15: lable 0, feature [5.7 4.4 1.5 0.4]
Example 16: lable 0, feature [5.4 3.9 1.3 0.4]
Example 17: lable 0, feature [5.1 3.5 1.4 0.3]
Example 18: lable 0, feature [5.7 3.8 1.7 0.3]
Example 19: lable 0, feature [5.1 3.8 1.5 0.3]
Example 20: lable 0, feature [5.4 3.4 1.7 0.2]
Example 21: lable 0, fe

In [19]:
import numpy as np
from sklearn import tree
test_idx = [0,50,100]
#training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data,test_idx,axis=0)
#testing data
test_target=iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data,train_target) 
print (test_target)
clf.predict(test_data)

[0 1 2]


array([0, 1, 2])

In [30]:
!pip install pydot
!pip install pydotplus

  Running setup.py bdist_wheel for pydotplus: started
  Running setup.py bdist_wheel for pydotplus: finished with status 'done'
  Stored in directory: C:\Users\avish\AppData\Local\pip\Cache\wheels\35\7b\ab\66fb7b2ac1f6df87475b09dc48e707b6e0de80a6d8444e3628
Successfully built pydotplus


In [37]:
#Viz Code from www.graphviz.org
#Copied from scikit-learn
from sklearn.externals.six import StringIO
import pydot
# import pydotplus
dot_data = StringIO()
tree.export_graphviz(clf,
                        out_file=dot_data,
                        feature_names=iris.feature_names,
                        class_names=iris.target_names,
                        filled=True, rounded=True,
                        impurity=False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")
# (graph.create_png("iris.png"))

AttributeError: 'list' object has no attribute 'write_pdf'

In [38]:
print(test_data[0],test_target[0])

[5.1 3.5 1.4 0.2] 0


In [39]:
print(iris.feature_names,iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']


In [41]:
print(test_data[1],test_target[1])
print(iris.feature_names,iris.target_names)

[7.  3.2 4.7 1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
